### PR TITLE
Rewrite of the package

### PR DESCRIPTION
**Pull request by Thomas-P**
Hello,

i need to use your api and thought i could refactor this a little bit. I removed the dependencies and fixed some issues with regex and multiple parameter statements. I also removed the dependencies in the test library, but i think it will need more test specification in the next time. 
By refactoring, i changed the algorithm a little bit, to handle keys with a point in them and added a added functionallity to create refer statements in the next time.

I hope the code is not so complex and understandable,

greetings Thomas

### CODE REVIEW

**Comment by ajb** [comment]
Thomas, this looks great, thanks so much. I haven't touched this repo in years, but maybe one of the other users of this library could review the code? (@mrcrgl are you still around?) 

Another option might be to simply create a new library, since if we merged this PR, I doubt that much of my original code would still be in-use. If you did that, I'd be more than happy to update the README to point folks to your new lib. And hey, you could choose a better name for it, too :D

**Comment by Thomas-P** [comment]
Hi,

it is possible to use it to an own library. I thought i could handle it by options, that defines how the lib work. The commit https://github.com/Thomas-P/mongoose-api-query/commit/2f9e17fd20d0d367a870c88f949e7978aaa67282 is the one, which implemented the functionallity of your library.

**Comment by nparsons08** [comment]
MERGE

**Comment by ajb** [comment]
Gonna stick with my comment above:

> Another option might be to simply create a new library, since if we merged this PR, I doubt that much of my original code would still be in-use. If you did that, I'd be more than happy to update the README to point folks to your new lib. And hey, you could choose a better name for it, too :D

**Pull request closed without merging**
